name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          load: true
          push: false
          tags: nomad-driver-podman/build:latest
      -
        name: build
        run: |
          docker cp $(docker create --name tc nomad-driver-podman/build:latest):/app/pkg/linux_amd64/nomad-driver-podman ./nomad-driver-podman-rootful && docker rm tc
          tar -czf nomad-driver-podman-rootful.tar.gz nomad-driver-podman-rootful
          sha256sum nomad-driver-podman-rootful.tar.gz | awk '{ print $1 }' > nomad-driver-podman-rootful.tar.gz.sha256
      -
        name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nomad-driver-podman-rootful.tar.gz
            nomad-driver-podman-rootful.tar.gz.sha256
